//genearting lucky number
//classy number codeforces
bool check(lli n){
  //check the condition on the number generated by funcn;
}
//generate lucky numbers and related stuff
void fun(lli n){
  if(n>limit or !check(n)){
    return;
  }
  list_of_lucky_number.push_back(n);
  loop("""type of numbers you want to generate"""){
    fun(n*10+ith number);
  }
}
////
