//genearting lucky number
//classy number codeforces
bool check(lli n){
  //check the condition on the number generated by funcn;
}
//generate lucky numbers and related stuff
void fun(lli n){
  if(n>limit or !check(n)){
    return;
  }
  list_of_lucky_number.push_back(n);
  loop("""type of numbers you want to generate"""){
    fun(n*10+ith number);
  }
}

////
//subtree count
void dfs(int v,int p = -1) {
	if (p == -1)depth[v] = 0;
	sub[v] = 1;
	for (auto u : g[v]) {
		if (u == p)continue;
		depth[u] = depth[v] + 1;
		dfs(u, v);
		sub[v] += sub[u];
	}
}
